# Generated by Django 4.2.16 on 2024-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Duration (days)"
            ),
        ),
    ]
