# Generated by Django 4.2.16 on 2024-11-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Node = apps.get_model("metrics", "Node")
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("metrics", "UserProfile")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        node_name = f"ELIXIR-{user.username.upper()}"
        node = Node.objects.using(db_alias).filter(name=node_name).first()
        UserProfile.objects.using(db_alias).get_or_create(user=user, node=node)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metrics", "0003_alter_demographic_event_alter_impact_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="metrics.node",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
