# Generated by Django 4.2.30 on 2026-04-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impact",
            name="event",
        ),
        migrations.RemoveField(
            model_name="impact",
            name="user",
        ),
        migrations.RemoveField(
            model_name="quality",
            name="event",
        ),
        migrations.RemoveField(
            model_name="quality",
            name="user",
        ),
        migrations.DeleteModel(
            name="Demographic",
        ),
        migrations.DeleteModel(
            name="Impact",
        ),
        migrations.DeleteModel(
            name="Quality",
        ),
    ]
